openapi: 3.0.0

info:
  title: Therm Hub API
  version: 20200720

servers:
  - url: http://localhost:3000
  
components:
  schemas:
    Condition:
      type: object
      properties:
        date: 
          type: string
          format: date
        condition: 
          type: string
          example: Mostly sunny, with a high near 82. Northeast wind 0 to 5 mph.
        day_temp: 
          type: integer
          description: Warning! Measured in 1/10 degrees F. Can be -1000 to indicate no value.
          example: 740
        night_temp: 
          type: integer
          description: Warning! Measured in 1/10 degrees F. Can be -1000 to indicate no value.
          example: 650
        
    NowResponse:
      type: object
      properties:
        forecast:
          type: array
          items: 
            $ref: '#/components/schemas/Condition'
        thermostats:
          type: array
          items:
            $ref: '#/components/schemas/Thermostat'
  
    Thermostat:
      type: object
      properties:
        name:
          type: string
          example: outside
        time:
          type: string
          format: date-time
        is_hygrostat:
          type: boolean
        temperature:
          type: integer
          description: Measured in 1/10 degrees F.
          example: 740
        relative_humidity:
          type: integer
          description: Integer % from 0-100. How much water can be in air is a function of temperature. RH can be used to calculate heat index.
          example: 55
    
    InstallResponse:
      type: object
      properties:
        ecobee_pin:
          type: string
          example: a263
        code:
          type: string
          example: czTAVXg4thWHhVosrdZPmf8wj0iiKa7A
    
paths:
  /version:
    get:
      summary: Gets the API version deployed on the server.
      responses:
        '200':
          description: A textual representation of the API version.
          content:
            text/plain:
              schema:
                type: string
                example: 20200720
    
  /now:
    get:
      summary: Gets the current conditions.
      responses:
        '200':
          description: The current conditions.
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/NowResponse'
    
  /time:
    get:
      summary: Gets the current time.
      responses:
        '200':
          description: The current time. Helpful for devices that do not have an RTC.
          content:
            text/plain:
              schema: 
                type: string
                example: 1595862295
                  
  /past:
    get:
      summary: Searches for thermostat readings in a date range.
      parameters:
        - in: query
          name: end_date
          schema:
            type: string
            example: 2020-07-30T00:00:00-05:00
          required: true
        - in: query
          name: start_date
          schema:
            type: string
            example: 2020-07-29T00:00:00-05:00
          required: true
      responses:
        '400':
          description: Bad request
        '500':
          description: Internal server error
        '200':
          description: The report.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NowResponse/properties/thermostats'
                
  /install/1:
    get:
      summary: Start the EcoBee install process.
      responses:
        '500':
          description: Internal server error
        '200':
          description: Data from EcoBee.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InstallResponse'
                
  /install/2:
    get:
      summary: Completes the EcoBee install process.
      parameters:
        - in: query
          name: code
          schema:
            type: string
          required: true
          example: czTAVXg4thWHhVosrdZPmf8wj0iiKa7A
      responses:
        '400':
          description: Bad request
        '500':
          description: Internal server error
        '200':
          description: Whether or not the process was successful.
          content:
            text/plain:
              schema:
                type: boolean

  /release-notes:
    get:
      summary: Gets API release notes
      responses:
        '200':
          description: Release notes.
          content:
            text/markdown:
              schema:
                type: string
              