name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-16.04

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --release --verbose
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: therm_hub
        path: target/release/therm_hub
    - name: Run tests
      run: cargo test --verbose
